default: &default
  adapter: postgresql
  encoding: unicode
  database: trainual
  pool: 5
  username: russ
  password:
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

